export const SET_NAME = 'SET_NAME';
export const SET_FAVORITE_CATEGORIES = 'SET_FAVORITE_CATEGORIES';
export const ADD_BOOKMARK_BOOK = 'ADD_BOOKMARK_BOOK';
export const DELETE_BOOKMARK_BOOK = 'DELETE_BOOKMARK_BOOK';
export const ADD_READING_BOOKS = 'ADD_READING_BOOKS';
