export const REQUEST_GET_BOOKS = 'REQUEST_GET_BOOKS';
export const SUCCESS_GET_BOOKS = 'SUCCESS_GET_BOOKS';
export const ERROR_GET_BOOKS = 'ERROR_GET_BOOKS';
export const LOAD_MORE_BOOKS = 'LOAD_MORE_BOOKS';
export const READ_BOOK = 'READ_BOOK';
export const RESET_BOOKS_REDUCERS = 'RESET_BOOKS_REDUCERS';
